Louis Goodall - Contours
ncsu-geoforall-lab/gis714-2022-tangible-landscape pull request #23
Opened 2022-04-06 15:29 UTC by lagoodal

2022-04-06 15:44 UTC, wenzeslaus commented
All the errors are related to JSON syntax. Try some online JSON validator. Try <https://jsonformatter.curiousconcept.com>. It seems to not only correctly describe the error from user point of view but also fix your file.

2022-04-06 15:56 UTC, lagoodal commented
I have moved the files to the activity folder and done the JSON formatting in the link you provided and the same error appears to be there. I don't know what to do.

2022-04-06 15:59 UTC, petrasovaa commented
> I have moved the files to the activity folder and done the JSON formatting in the link you provided and the same error appears to be there. I don't know what to do.

When you click Details on the failed check, you can see:
```
AssertionError: 'Example Contributor' == 'Example Contributor' : Value of author in a task in louis_goodall.json matches value from the example file simple_example.json. author value should be different from the provided example. Change the author value in louis_goodall.json)
```

2022-04-06 16:02 UTC, petrasovaa commented on activities/louis_goodall.py
> +        "r.contour", input=scanned_elev, output="contours", levels=[15, 30, 45]
You don't pass the env variable, see instructions in simple_example.py

2022-04-06 16:03 UTC, petrasovaa commented on activities/louis_goodall.json
> +               "d.rast",
```suggestion
               "d.vect",
```

2022-04-11 21:14 UTC, petrasovaa requested changes
If you check the rendered result of your PR (see [instructions](https://github.com/ncsu-geoforall-lab/gis714-2022-tangible-landscape#after-opening-pr)), the image is empty because the elevation of the contours you specified is less than the elevation of the raster. It would be better to for example to dynamically choose the levels or contour step based on the elevation range. That would also make this application little bit more sophisticated than it is now.

2022-04-13 02:12 UTC, petrasovaa commented
If you check the rendered result of your PR (see [instructions](https://github.com/ncsu-geoforall-lab/gis714-2022-tangible-landscape#after-opening-pr)), the image is empty because the elevation of the contours you specified is less than the elevation of the raster. It would be better to for example to dynamically choose the levels or contour step based on the elevation range. That would also make this application little bit more sophisticated than it is now.

2022-04-13 03:04 UTC, petrasovaa commented
Third time's the charm!

2022-04-13 03:04 UTC, merged