reckling tangible landscape activity
ncsu-geoforall-lab/gis714-2022-tangible-landscape pull request #33
Opened 2022-04-10 02:41 UTC by skreckli

Add tangible landscape activity

2022-04-11 15:35 UTC, wenzeslaus commented on activities/sreckling.py
> +def runsunshadow(scanned_elev, env, **kwargs):
See line 7 above or the _File content / Python files_ check:

```
... File activities/sreckling.py does not contain any functions with the 'run_' prefix
```

2022-04-11 21:08 UTC, petrasovaa requested changes
If you check the rendered result of your PR (see [instructions](https://github.com/ncsu-geoforall-lab/gis714-2022-tangible-landscape#after-opening-pr)), the image is empty because there are no shadows for that landscape at 10.30. So I suggest changing that to e.g. 7am. We can place e.g. a building on the physical model, so the shading will be more visible then, but changing that time will overall result in more interesting results.

Also, it may be useful to compute shaded relief and add it to the rendered layers in the json file.

2022-04-12 20:00 UTC, skreckli commented
Thanks for the suggestions Anna.  I've adjusted the time to 8:30am and added a function for r.relief.  I realize that the output of r.sunmask is empty when the input is the elevation.  I was going to bring blocks to cast shadows but I think using the buildings you have sounds even better!

2022-04-12 20:08 UTC, petrasovaa commented on activities/sreckling.json
> +        ["d.rast", "map=relief"]
```suggestion
        ["d.rast", "map=relief"],
        ["d.rast", "map=shadow"]
```

2022-04-13 02:04 UTC, petrasovaa approved these changes

2022-04-13 02:04 UTC, merged